### ISSUE TITLE
Set-StrictMode in tests

### ISSUE THREAD

**Issue by jborean93** [Phil-Factor/PSYaml#25]
Hi, apologise for the extra noise but I came across the usage of `Set-StrictMode` in your tests like https://github.com/Phil-Factor/PSYaml/blob/master/Tests/PSYaml.ConvertFrom.Tests.ps1#L64. Your description indicates that the `-Version` refers to the PowerShell version it is testing against but it's my understanding that StrictMode has 1.0, 2.0, and latest which are specific rule sets and not PS version compatibilities. Am I misunderstanding the use of `Set-StrictMode` here or are those extra tests not doing what they should be doing?

**Comment by Phil-Factor** [comment]
Thanks for letting me know. 

As far as I know these tests are no longer being maintained by the contributor who added them.  I have tried to contact him several times.  As these tests seem to  have let through quite a few bugs, I'll probably replace them with something better. I have a large bank of tests but they don't look at all pretty at the moment.

You are right. the parameter 'version' in StrictMode  refers to the version of the tests that are applies so that 1.0 prohibits references to uninitialized variables, except for uninitialized variables in strings, whereas 2.0 prohibits references to uninitialized variables. This includes uninitialized variables in strings. It also prohibits references to non-existent properties of an object as well as  function calls that use the syntax for calling methods. It also prohibits a variable without a name (${}).

It is best to duck this and just specify 'Latest'.

**Comment by jborean93** [comment]
Thanks for the clarification
